-- Generated by scripts/generate-seed.mjs. Sample data for development and demos.

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('valentinos-pizzeria', 'Valentino''s Pizzeria', 'Authentic Neapolitan pizza made with imported Italian ingredients and wood-fired in our custom brick oven.', array['Italian', 'Pizza']::text[], 2, '1501 S Congress Ave', 'Austin', 'TX', '78704', 30.2456, -97.7499, '{"monday":{"open":"11:00","close":"22:00"},"tuesday":{"open":"11:00","close":"22:00"},"wednesday":{"open":"11:00","close":"22:00"},"thursday":{"open":"11:00","close":"23:00"},"friday":{"open":"11:00","close":"23:00"},"saturday":{"open":"11:00","close":"23:00"},"sunday":{"open":"12:00","close":"21:00"}}'::jsonb, 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800', array['outdoor_seating', 'wifi', 'full_bar']::text[], 4.8, 2450)
on conflict (slug) do nothing;

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('uchi', 'Uchi', 'Award-winning contemporary Japanese restaurant featuring innovative sushi and seasonal omakase.', array['Japanese', 'Sushi']::text[], 4, '801 S Lamar Blvd', 'Austin', 'TX', '78704', 30.2571, -97.7612, '{"monday":{"open":"17:00","close":"22:00"},"tuesday":{"open":"17:00","close":"22:00"},"wednesday":{"open":"17:00","close":"22:00"},"thursday":{"open":"17:00","close":"22:00"},"friday":{"open":"17:00","close":"23:00"},"saturday":{"open":"17:00","close":"23:00"},"sunday":{"open":"17:00","close":"21:00"}}'::jsonb, 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800', array['full_bar', 'private_dining', 'valet']::text[], 4.9, 3200)
on conflict (slug) do nothing;

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('franklin-barbecue', 'Franklin Barbecue', 'Legendary Texas BBQ known for melt-in-your-mouth brisket. Worth every minute of the wait.', array['BBQ', 'American']::text[], 2, '900 E 11th St', 'Austin', 'TX', '78702', 30.2701, -97.7253, '{"tuesday":{"open":"11:00","close":"15:00"},"wednesday":{"open":"11:00","close":"15:00"},"thursday":{"open":"11:00","close":"15:00"},"friday":{"open":"11:00","close":"15:00"},"saturday":{"open":"11:00","close":"15:00"},"sunday":{"open":"11:00","close":"15:00"}}'::jsonb, 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800', array['outdoor_seating', 'byob']::text[], 4.7, 8500)
on conflict (slug) do nothing;

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('torchys-tacos', 'Torchy''s Tacos', 'Damn good tacos with creative flavor combinations. A true Austin original.', array['Mexican', 'Tacos']::text[], 1, '1311 S 1st St', 'Austin', 'TX', '78704', 30.2512, -97.7551, '{"monday":{"open":"07:00","close":"22:00"},"tuesday":{"open":"07:00","close":"22:00"},"wednesday":{"open":"07:00","close":"22:00"},"thursday":{"open":"07:00","close":"22:00"},"friday":{"open":"07:00","close":"23:00"},"saturday":{"open":"08:00","close":"23:00"},"sunday":{"open":"08:00","close":"22:00"}}'::jsonb, 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800', array['outdoor_seating', 'breakfast']::text[], 4.5, 4200)
on conflict (slug) do nothing;

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('suerte', 'Suerte', 'Modern Mexican restaurant celebrating heritage ingredients with contemporary techniques.', array['Mexican', 'Contemporary']::text[], 3, '1800 E 6th St', 'Austin', 'TX', '78702', 30.2621, -97.7205, '{"monday":{"open":"17:00","close":"22:00"},"tuesday":{"open":"17:00","close":"22:00"},"wednesday":{"open":"17:00","close":"22:00"},"thursday":{"open":"17:00","close":"22:00"},"friday":{"open":"17:00","close":"23:00"},"saturday":{"open":"17:00","close":"23:00"},"sunday":{"open":"17:00","close":"21:00"}}'::jsonb, 'https://images.unsplash.com/photo-1625167171794-e72fa4ba67c8?w=800', array['full_bar', 'outdoor_seating']::text[], 4.6, 1890)
on conflict (slug) do nothing;

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('ramen-tatsu-ya', 'Ramen Tatsu-Ya', 'Soul-warming ramen with rich, complex broths simmered for over 20 hours.', array['Japanese', 'Ramen']::text[], 2, '8557 Research Blvd', 'Austin', 'TX', '78758', 30.3582, -97.7195, '{"monday":{"open":"11:00","close":"22:00"},"tuesday":{"open":"11:00","close":"22:00"},"wednesday":{"open":"11:00","close":"22:00"},"thursday":{"open":"11:00","close":"22:00"},"friday":{"open":"11:00","close":"23:00"},"saturday":{"open":"11:00","close":"23:00"},"sunday":{"open":"11:00","close":"21:00"}}'::jsonb, 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800', array['no_reservations', 'counter_seating']::text[], 4.7, 3100)
on conflict (slug) do nothing;

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('odd-duck', 'Odd Duck', 'Farm-to-table small plates showcasing the best of Texas ingredients.', array['American', 'Farm-to-table']::text[], 3, '1201 S Lamar Blvd', 'Austin', 'TX', '78704', 30.2485, -97.7649, '{"tuesday":{"open":"17:00","close":"22:00"},"wednesday":{"open":"17:00","close":"22:00"},"thursday":{"open":"17:00","close":"22:00"},"friday":{"open":"17:00","close":"23:00"},"saturday":{"open":"10:00","close":"23:00"},"sunday":{"open":"10:00","close":"14:00"}}'::jsonb, 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', array['brunch', 'outdoor_seating', 'full_bar']::text[], 4.5, 2340)
on conflict (slug) do nothing;

insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)
values ('thai-fresh', 'Thai Fresh', 'Organic Thai cuisine made from scratch using family recipes and local ingredients.', array['Thai', 'Organic']::text[], 2, '909 W Mary St', 'Austin', 'TX', '78704', 30.2461, -97.7584, '{"monday":{"open":"11:00","close":"21:00"},"tuesday":{"open":"11:00","close":"21:00"},"wednesday":{"open":"11:00","close":"21:00"},"thursday":{"open":"11:00","close":"21:00"},"friday":{"open":"11:00","close":"22:00"},"saturday":{"open":"11:00","close":"22:00"},"sunday":{"open":"11:00","close":"21:00"}}'::jsonb, 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800', array['vegetarian_friendly', 'outdoor_seating', 'cooking_classes']::text[], 4.4, 1560)
on conflict (slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'margherita-pizza', 'Margherita Pizza', 'San Marzano tomatoes, fresh mozzarella, basil, extra virgin olive oil', 'Pizza', 1899, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800', array['vegetarian']::text[], true, 0, '{"sizes":[{"id":"personal","name":"Personal (10\")","priceModifier":-400},{"id":"medium","name":"Medium (14\")","priceModifier":0},{"id":"large","name":"Large (16\")","priceModifier":400}],"crustOptions":[{"id":"traditional","name":"Traditional Hand Tossed","priceModifier":0},{"id":"thin","name":"Thin & Crispy","priceModifier":100},{"id":"deep","name":"Deep Dish","priceModifier":200},{"id":"gf","name":"Gluten Free","priceModifier":300}],"toppings":[{"id":"extra_cheese","name":"Extra Cheese","price":150},{"id":"mushrooms","name":"Mushrooms","price":100},{"id":"pepperoni","name":"Pepperoni","price":150},{"id":"sausage","name":"Italian Sausage","price":150},{"id":"olives","name":"Black Olives","price":100},{"id":"peppers","name":"Bell Peppers","price":100},{"id":"onions","name":"Red Onions","price":75},{"id":"basil","name":"Fresh Basil","price":50}],"maxToppings":4,"comboOptions":{"available":true,"discount":300,"price":599,"description":"Add a drink and side","drinks":["Coke","Diet Coke","Sprite","Iced Tea","Lemonade"],"sides":[{"id":"salad","name":"Garden Salad","priceModifier":0},{"id":"caesar","name":"Caesar Salad","priceModifier":100},{"id":"knots","name":"Garlic Knots","priceModifier":0},{"id":"wings","name":"Buffalo Wings (6pc)","priceModifier":200}]}}'::jsonb, 4.9, 342
from public.restaurants r where r.slug = 'valentinos-pizzeria'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'pepperoni-lovers', 'Pepperoni Lovers', 'Double pepperoni, mozzarella, marinara sauce, Italian herbs', 'Pizza', 2199, 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800', array[]::text[], true, 1, '{"sizes":[{"id":"personal","name":"Personal (10\")","priceModifier":-400},{"id":"medium","name":"Medium (14\")","priceModifier":0},{"id":"large","name":"Large (16\")","priceModifier":400}],"crustOptions":[{"id":"traditional","name":"Traditional Hand Tossed","priceModifier":0},{"id":"thin","name":"Thin & Crispy","priceModifier":100},{"id":"deep","name":"Deep Dish","priceModifier":200}],"toppings":[{"id":"extra_cheese","name":"Extra Cheese","price":150},{"id":"mushrooms","name":"Mushrooms","price":100},{"id":"olives","name":"Black Olives","price":100},{"id":"peppers","name":"Bell Peppers","price":100},{"id":"jalapenos","name":"Jalapenos","price":75}],"maxToppings":3}'::jsonb, 4.7, 289
from public.restaurants r where r.slug = 'valentinos-pizzeria'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'tiramisu', 'Tiramisu', 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone', 'Desserts', 999, 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800', array['vegetarian']::text[], false, 2, '{}'::jsonb, 4.8, 156
from public.restaurants r where r.slug = 'valentinos-pizzeria'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'caesar-salad', 'Caesar Salad', 'Romaine, parmesan, croutons, house-made Caesar dressing', 'Salads', 1299, 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800', array['vegetarian']::text[], false, 3, '{"addOns":[{"id":"chicken","name":"Grilled Chicken","price":400},{"id":"shrimp","name":"Grilled Shrimp","price":600},{"id":"anchovies","name":"Anchovies","price":200}]}'::jsonb, 4.4, 98
from public.restaurants r where r.slug = 'valentinos-pizzeria'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'trailer-park', 'Trailer Park', 'Fried chicken, green chiles, lettuce, pico, cheese, poblano sauce. Get it "Trashy" - add queso!', 'Tacos', 450, 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800', array[]::text[], true, 0, '{"style":[{"id":"regular","name":"Regular","priceModifier":0},{"id":"trashy","name":"Make it Trashy (add queso)","priceModifier":100}],"tortilla":[{"id":"flour","name":"Flour Tortilla","priceModifier":0},{"id":"corn","name":"Corn Tortilla","priceModifier":0}],"extras":[{"id":"extra_cheese","name":"Extra Cheese","price":75},{"id":"guac","name":"Guacamole","price":150},{"id":"jalapenos","name":"Fresh Jalapenos","price":50}]}'::jsonb, 4.8, 1205
from public.restaurants r where r.slug = 'torchys-tacos'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'democrat', 'Democrat', 'Barbacoa, avocado, cotija, cilantro, onions, lime, salsa verde', 'Tacos', 495, 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800', array['gluten-free']::text[], true, 1, '{"tortilla":[{"id":"flour","name":"Flour Tortilla","priceModifier":0},{"id":"corn","name":"Corn Tortilla","priceModifier":0}],"extras":[{"id":"extra_meat","name":"Extra Barbacoa","price":200},{"id":"guac","name":"Extra Guacamole","price":150},{"id":"sour_cream","name":"Sour Cream","price":50}]}'::jsonb, 4.6, 876
from public.restaurants r where r.slug = 'torchys-tacos'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'green-chile-queso', 'Green Chile Queso', 'House-made queso with roasted green chiles, served with chips', 'Starters', 525, 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=800', array['vegetarian', 'gluten-free']::text[], true, 2, '{"size":[{"id":"regular","name":"Regular","priceModifier":0},{"id":"large","name":"Large","priceModifier":250}],"addOns":[{"id":"guac","name":"Add Guacamole","price":150},{"id":"beef","name":"Add Ground Beef","price":200},{"id":"chorizo","name":"Add Chorizo","price":200}]}'::jsonb, 4.7, 654
from public.restaurants r where r.slug = 'torchys-tacos'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'breakfast-taco-migas', 'Breakfast Taco - Migas', 'Eggs, crispy tortilla strips, cheese, pico, salsa verde', 'Breakfast', 375, 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=800', array['vegetarian']::text[], false, 3, '{"tortilla":[{"id":"flour","name":"Flour Tortilla","priceModifier":0},{"id":"corn","name":"Corn Tortilla","priceModifier":0}],"addOns":[{"id":"bacon","name":"Add Bacon","price":150},{"id":"chorizo","name":"Add Chorizo","price":150},{"id":"avocado","name":"Add Avocado","price":100}]}'::jsonb, 4.5, 432
from public.restaurants r where r.slug = 'torchys-tacos'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'tonkotsu-original', 'Tonkotsu Original', '18-hour pork bone broth, chashu pork, seasoned egg, green onions, nori', 'Ramen', 1500, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800', array[]::text[], true, 0, '{"noodleTexture":[{"id":"soft","name":"Soft","priceModifier":0},{"id":"regular","name":"Regular","priceModifier":0},{"id":"firm","name":"Firm","priceModifier":0}],"brothRichness":[{"id":"light","name":"Light","priceModifier":0},{"id":"regular","name":"Regular","priceModifier":0},{"id":"rich","name":"Rich","priceModifier":0}],"spiceLevel":[{"id":"none","name":"No Spice","priceModifier":0},{"id":"mild","name":"Mild","priceModifier":0},{"id":"medium","name":"Medium","priceModifier":0},{"id":"hot","name":"Hot","priceModifier":0}],"extras":[{"id":"extra_egg","name":"Extra Egg","price":200},{"id":"extra_chashu","name":"Extra Chashu (3pc)","price":400},{"id":"extra_noodles","name":"Extra Noodles","price":250},{"id":"corn","name":"Sweet Corn","price":100},{"id":"garlic","name":"Roasted Garlic","price":75},{"id":"mushrooms","name":"Wood Ear Mushrooms","price":150}]}'::jsonb, 4.9, 1567
from public.restaurants r where r.slug = 'ramen-tatsu-ya'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'tsukemen', 'Tsukemen', 'Dipping ramen with thick noodles and concentrated pork broth', 'Ramen', 1700, 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800', array[]::text[], true, 1, '{"size":[{"id":"regular","name":"Regular","priceModifier":0},{"id":"large","name":"Large Noodles","priceModifier":300}],"extras":[{"id":"extra_egg","name":"Extra Egg","price":200},{"id":"extra_chashu","name":"Extra Chashu","price":400}]}'::jsonb, 4.8, 892
from public.restaurants r where r.slug = 'ramen-tatsu-ya'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'vegetarian-ramen', 'Vegetarian Ramen', 'Mushroom and kombu broth, tofu, seasonal vegetables, nori', 'Ramen', 1400, 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=800', array['vegetarian', 'vegan-option']::text[], false, 2, '{"noodleTexture":[{"id":"soft","name":"Soft","priceModifier":0},{"id":"regular","name":"Regular","priceModifier":0},{"id":"firm","name":"Firm","priceModifier":0}],"extras":[{"id":"extra_tofu","name":"Extra Tofu","price":200},{"id":"corn","name":"Sweet Corn","price":100},{"id":"mushrooms","name":"Extra Mushrooms","price":150}]}'::jsonb, 4.5, 324
from public.restaurants r where r.slug = 'ramen-tatsu-ya'
on conflict (restaurant_id, slug) do nothing;

insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)
select r.id, 'gyoza', 'Gyoza', 'Pan-fried pork dumplings with ponzu dipping sauce', 'Appetizers', 800, 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800', array[]::text[], false, 3, '{"quantity":[{"id":"6pc","name":"6 pieces","priceModifier":0},{"id":"12pc","name":"12 pieces","priceModifier":600}]}'::jsonb, 4.6, 456
from public.restaurants r where r.slug = 'ramen-tatsu-ya'
on conflict (restaurant_id, slug) do nothing;

