// Generates supabase/seed.sql from the sample data in src/data.
// Usage: node scripts/generate-seed.mjs > supabase/seed.sql
import { restaurants } from '../src/data/restaurants.js';
import { menuItems } from '../src/data/menuItems.js';

const PRICE_KEYS = new Set(['priceModifier', 'price', 'discount']);

const toCents = (dollars) => Math.round(dollars * 100);

// Convert every price inside a customizations object from dollars to cents
function priceTreeToCents(value, key) {
  if (Array.isArray(value)) return value.map((v) => priceTreeToCents(v));
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, priceTreeToCents(v, k)])
    );
  }
  if (PRICE_KEYS.has(key) && typeof value === 'number') return toCents(value);
  return value;
}

const slugify = (s) =>
  s.toLowerCase().normalize('NFKD').replace(/['’]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const lit = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (a) => `array[${a.map(lit).join(', ')}]::text[]`;
const json = (o) => `${lit(JSON.stringify(o))}::jsonb`;

const out = ['-- Generated by scripts/generate-seed.mjs. Sample data for development and demos.', ''];

const slugById = {};
for (const r of restaurants) {
  const slug = slugify(r.name);
  slugById[r.id] = slug;
  out.push(
    `insert into public.restaurants (slug, name, description, cuisine, price_level, address, city, state, zip_code, lat, lng, hours, photo_url, features, rating, review_count)`,
    `values (${[
      lit(slug), lit(r.name), lit(r.description), arr(r.cuisine), r.priceLevel,
      lit(r.location.address), lit(r.location.city), lit(r.location.state), lit(r.location.zipCode),
      r.location.coordinates.lat, r.location.coordinates.lng, json(r.hours), lit(r.photo),
      arr(r.features), r.rating, r.reviewCount,
    ].join(', ')})`,
    `on conflict (slug) do nothing;`,
    ''
  );
}

for (const [restId, items] of Object.entries(menuItems)) {
  items.forEach((item, i) => {
    out.push(
      `insert into public.menu_items (restaurant_id, slug, name, description, category, base_price_cents, photo_url, dietary_info, is_popular, sort_order, customizations, rating, review_count)`,
      `select r.id, ${[
        lit(slugify(item.name)), lit(item.name), lit(item.description), lit(item.category),
        toCents(item.basePrice), lit(item.photo), arr(item.dietaryInfo || []), !!item.popular, i,
        json(priceTreeToCents(item.customizations || {})), item.rating ?? 0, item.reviewCount ?? 0,
      ].join(', ')}`,
      `from public.restaurants r where r.slug = ${lit(slugById[restId])}`,
      `on conflict (restaurant_id, slug) do nothing;`,
      ''
    );
  });
}

console.log(out.join('\n'));
